// <auto-generated />
using System;
using DietAndExercise.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DietAndExercise.Data.Migrations
{
    [DbContext(typeof(DietAndExerciseDbContext))]
    partial class DietAndExerciseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("DietAndExercise.Data.Entities.DayRecordEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesBurned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CaloriesConsumed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("ExerciseNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FoodIntakeNotes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("WeightLb")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Date")
                        .IsUnique();

                    b.ToTable("DayRecords");
                });

            modelBuilder.Entity("DietAndExercise.Data.Entities.ExerciseEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DayRecordId");

                    b.ToTable("ExerciseEntries");
                });

            modelBuilder.Entity("DietAndExercise.Data.Entities.FoodEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("DayRecordId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DayRecordId");

                    b.ToTable("FoodEntries");
                });

            modelBuilder.Entity("DietAndExercise.Data.Entities.ExerciseEntry", b =>
                {
                    b.HasOne("DietAndExercise.Data.Entities.DayRecordEntity", "DayRecord")
                        .WithMany("ExerciseEntries")
                        .HasForeignKey("DayRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayRecord");
                });

            modelBuilder.Entity("DietAndExercise.Data.Entities.FoodEntry", b =>
                {
                    b.HasOne("DietAndExercise.Data.Entities.DayRecordEntity", "DayRecord")
                        .WithMany("FoodEntries")
                        .HasForeignKey("DayRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DayRecord");
                });

            modelBuilder.Entity("DietAndExercise.Data.Entities.DayRecordEntity", b =>
                {
                    b.Navigation("ExerciseEntries");

                    b.Navigation("FoodEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
